### ISSUE TITLE
[Users] Import a list of users from CSV file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#10]
As an admin user I want to be able to import a list of users in CSV format.
The CSV will contain the following information, on each row:
- Nume
- Prenume
- Email
- Telefon
- Judet
- Organizatie

Before importing, the admin user uploading the file should confirm that the information parsed from CSV file is correct.
The User Controller should be enhanced with a new endpoint that parses the CSV and returns a list of results, and a new endpoint that receives the list of results and persists them to the database.

![Adauga membri (1)](https://user-images.githubusercontent.com/15039873/58744539-26a5b480-83f9-11e9-9c07-9e3f7cca4ac9.png)

**Comment by mihairinzis** [comment]
@mihairinzis

**Comment by RaduCStefanescu** [comment]
In progress @mihairinzis

**Comment by RaduCStefanescu** [comment]
This issue has been implemented in #30
