### ISSUE TITLE
[Users] Implement user roles

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#27]
Users created in the application should have different roles.
The roles should be:
- ADMIN (can upload document, create new users, assign part of the documents, etc)
- CONTRIBUTOR (can only comment on documents)

The information should be part of the JWT token generated.

**Comment by mihairinzis** [comment]
in progress by @georgebejan

**Comment by RaduCStefanescu** [comment]
Fixed in #41 can be closed
