### ISSUE TITLE
[Users] Send confirmation email when user created in platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#28]
As an admin, when I create a new user in the platform, I want to send a confirmation email to that user.
The user receiving the email should also be redirected to the signup page, to fill in it's credentials and create his account in the platform.
In the sign up process, the user should be compelled to use the email address on which he received the email. This can be forced by using the unique id as part of the sign up URL to be able to match with the account created by the admin.

**Comment by mihairinzis** [comment]
in progress @mihairinzis

**Comment by RaduCStefanescu** [comment]
Fixed in #42 can be closed
