### ISSUE TITLE
[Generic] Add Swagger support

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#36]
Add support for Swagger API documentation.

**Comment by Andu033** [comment]
I want to work on this.

**Comment by RaduCStefanescu** [comment]
@Andu033 the issue is yours, but please wait for the fix on https://github.com/code4romania/legal-consultation-api/issues/35 
It will modify the folder structure of the project.
Thank you!

**Comment by RaduCStefanescu** [comment]
@Andu033 changes merged, you can start implementing the issue, but please update your develop branch first.
Thanks!

**Comment by RaduCStefanescu** [comment]
This issue was resolved in #56 
Closing it
