### ISSUE TITLE
[Documents] Define entity datamodel for document metadata

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#5]
An entity datamodel needs to be defined to hold the metadata information for an uploaded document.

Please have a look at the wireframe for more informatio:
![Incarca document](https://user-images.githubusercontent.com/15039873/58744397-ffe67e80-83f6-11e9-93f6-6b004b292bc3.png)

**Comment by Andu033** [comment]
Can I claim this one?

**Comment by RaduCStefanescu** [comment]
Fixed in #18
