### ISSUE TITLE
[Infrastructure] Run application in Docker

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#51]
As part of the easy deployment of the project, we need to have a Docker image containing the application and all the dependencies:
- MySQL 
- MailHog

**Comment by mihairinzis** [comment]
in progress @mihairinzis

**Comment by RaduCStefanescu** [comment]
After discussing with @mihairinzis this issue will cover also running the tests inside the Docker container.

**Comment by RaduCStefanescu** [comment]
Already covered in https://github.com/code4romania/legal-consultation-api/pull/53
The issue can be closed.
