### ISSUE TITLE
[Documents] Define entity datamodel for document breakdown

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#6]
An entity datamodel needs to be defined for persisting the information about the units composing a document breakdown.

Please check out the wireframes for additional information:
![Doc breakdown edit](https://user-images.githubusercontent.com/15039873/58744410-476d0a80-83f7-11e9-8fe3-4282307df58b.png)

**Comment by Andu033** [comment]
I can take it too?

**Comment by RaduCStefanescu** [comment]
Closing this one, as it is implemented in #20
