### ISSUE TITLE
[Users] View all users in the platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#8]
As an admin user of the Legal Consultation platform I want to be able to see all the users defined in the platform.
A new datamodel entity should be implemented to hold user metadata.
The new datamodel entity should be linked to an existing ApplicationUser account through username or email.
A User Controller needs to be implemented for retrieving all the new datamodel entities from the platform. The endpoint should implement pagination.

![Manage members and roles](https://user-images.githubusercontent.com/15039873/58744440-e6920200-83f7-11e9-9b90-b1f801104035.png)

**Comment by mihairinzis** [comment]
@mihairinzis

**Comment by RaduCStefanescu** [comment]
In progress @mihairinzis
