### ISSUE TITLE
[Users] Add single user to platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/legal-consultation-api#9]
As an admin user of the legal consultation platform I want to be able to add a single user to the platform.

The user controller needs to be enhanced to implement Create operation on user resource.
The DTO object should have the following attributes:
- Nume
- Prenume
- Email
- Telefon
- Judet
- Organizatie

**Comment by Andu033** [comment]
I want to work on that.

**Comment by RaduCStefanescu** [comment]
In progress @Andu033

**Comment by Andu033** [comment]
@RaduCStefanescu The issue says to enhance user controller but i don't see any user cotroller. It exists?

**Comment by RaduCStefanescu** [comment]
@Andu033 In the great scheme of things, this issue https://github.com/code4romania/legal-consultation-api/issues/8, which is WIP at @mihairinzis should be implemented before the one you are working on. That issue has a task for creating a User Controller, and this issue has a task of enhancing that user controller for CRUD operations.
So @Andu033 can you please wait for a commit with changes on the mentioned issue #8 ?
Thanks!

**Comment by RaduCStefanescu** [comment]
@Andu033 this issue has been implemented by @mihairinzis under #31 
Could you please choose another issue from the outstanding ones? Thanks!

**Comment by RaduCStefanescu** [comment]
Issue can be closed, it has been implemented under #31
